default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple


Hummingbird:
    init_path: .\models\A_floatingisland\Hummingbird
    time_horizon: 128
    batch_size: 2048
    buffer_size: 20480
    hidden_units: 256
    max_steps: 5.0e6
    behavioral_cloning:
        demo_path: C:\Users\costa\Documents\AMaria\TEO\Thesis\ML-Agents\HummingbirdsOK\Assets\Demonstrations\floatingisland.demo
        strength: 0.5
        steps: 150000
    reward_signals:
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: C:\Users\costa\Documents\AMaria\TEO\Thesis\ML-Agents\HummingbirdsOK\Assets\Demonstrations\floatingisland.demo
